config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users
  resources :messages, only: :create
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user 
  has_many :notifications, dependent: :destroy
  attachment :image
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, dependent: :destroy
  attachment :message_image
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :tweet, optional: true
  belongs_to :comment, optional: true
  belongs_to :message, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/room.rb
class Room < ApplicationRecord
  attachment :message_image
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end


  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      tweet_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @comment = Comment.create(comment_params)
    @tweet = @comment.tweet
    redirect_to "/tweets/#{@comment.tweet.id}"
    @tweet.create_notification_comment!(current_user, @comment.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :image).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(3)
    @comments = Comment.all.order("created_at DESC").page(params[:page]).per(7)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :message_image, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    gon.api_key = ENV['API_KEY']
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(6)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweet_path(@tweet), notice: "投稿しました"
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
    if @tweet.user != current_user
      redirect_to tweets_path, alert: "不正なアクセスです"
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet), notice: "更新しました"
    else
      render :edit
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :body, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.includes(:tweet).order("created_at DESC").page(params[:page]).per(10)
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
    @visitor = notification.visitor
    @visitor_comment = notification.comment_id
    case notification.action
      when "comment" then
        @comment = Comment.find_by(id: @visitor_comment)&.text
        tag.a(@visitor.username, href:user_path(@visitor), style:"font-weight: bold;")+"さんが"+tag.a('あなたの投稿', href:tweet_path(notification.tweet.id), style:"font-weight: bold;")+"に回答しました"
    end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/rooms/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        DM（個人トーク）
      </h1>
    </div>
  </div>
</section>

<div class="media is-ancestor">
  <div class="tile">
    <% @entries.each do |e| %>
      <div class="tile is-parent">
        <article class="tile is-child box">
          <p class="title", style="text-align: center;"><a href="/users/<%=e.user.id %>"><%= e.user.username%>さん</a></p>
          <figure class="image is-4by3">
            <%= link_to user_path(e.user.id) do %>
              <%= attachment_image_tag e.user, :profile_image, fallback: "no_image.png", class: "profile_image"%>
            <% end %>
          </figure>
        </article>
      </div>
    <% end %>
  </div>
</div>

<hr>
<% @messages.each do |m| %>
  <article class="media">
    <% if m.present? %>
      <figure class="media-left">
        <p class="image is-64x64">
          <%= link_to user_path(m.user.id) do %>
            <%= attachment_image_tag m.user, :profile_image, fallback: "no_image.png" %>
          <% end %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <p>
            <strong><a href="/users/<%= m.user_id %>"><%= m.user.username %></a></strong>
            <br>
            <%= m.content %>
            <br>
            <% if m.message_image.present? %>
              <div class="column is-4">
                <div class="card">
                  <div class="card-image">
                    <figure class="image is-4by3">
                      <%= link_to Refile.attachment_url(m, :message_image), "data-lightbox"=>"abc" do %>
                        <%= attachment_image_tag m, :message_image %>
                      <% end %>
                    </figure>
                  </div>
                </div>
              </div>
            <% else %>
            <% end %>
          </p>
        </div>
      </div>
    <% else %>
      <h3 class="text-center">メッセージはまだありません</h3>
    <% end %>
  </article>
<% end %>

<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= attachment_image_tag current_user, :profile_image, fallback: "no_image.png"%>
    </p>
  </figure>
  <div class="media-content">
    <%= form_for @message do |f| %>
      <div class="field">
        <p class="control">
          <%= f.text_area :content, :placeholder => "メッセージを入力して下さい", class: "textarea" %>
        </p>
      </div>
      <div class="field">
        <div class="file is-info has-name">
          <label class="file-label">
            <%= f.attachment_field :message_image, class: "input" %>
          </label>
        </div>
      </div>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <nav class="level">
        <div class="level-left">
          <div class="level-item". style="margin-bottom: 50px;">
            <%= f.submit "送信する", class:"button is-link" %>
          </div>
        </div>
      </nav>
    <% end %>
  </div>
</article>

<div class="column has-background-light">
  <section class="hero", style="text-align: center;">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          ビデオ通話
        </h1>
      </div>
    </div>
  </section>
  <div class="session", style="margin: 0 auto;">
    <div id="call-media-contents">
      <div class="session has-text-centered", style="margin-bottom: 40px;">
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">My-ID</label>
          </div>
          <div class="field-body">
            <div class="field">
              <p class="control">
                <textarea class="input", id="my-id", type="text"></textarea>
              </p>
            </div>
            <div class="field has-addons", style="max-width: 90%;">
              <p class="control">
                <button class="button", id="copy-btn">
                  <span class="icon is-small">
                    <i class="far fa-copy"></i>
                  </span>
                  <span>IDをコピー</span>
                </button>
              </p>
            </div>
          </div>
        </div>

        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Partner-ID</label>
          </div>
          <div class="field-body">
            <div class="field">
              <p class="control">
                <div class="field is-grouped", style="max-width: 90%;">
                  <p class="control is-expanded">
                    <input class="input is-focused", id="their-id" type="text" placeholder="相手のIDを入力">
                  </p>
                  <p class="control">
                    <a class="button is-link　is-rounded", id="make-call">
                      電話をかける
                    </a>
                  </p>
                </div>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="session", style="text-align: center;">
        <div class="call-media-partner", style="width: 50%; margin: 0 auto; text-align: center;">
          <video id="their-video" autoplay muted playsinline, style="background-color: black;"></video>
        </div>
        <div class="call-media-myself", style="width: 30%; margin: 0 auto;">
          <video id="my-video" autoplay muted playsinline></video>
        </div>
        <button class="button is-danger is-rounded", id="stop-button", style="margin: 40px;">終話する</button>
      </div>
    </div>
  <div>

  <div class="session has-text-centered" id="before-call-contents">
    <article class="message is-large">
      <div class="message-header has-text-centered">
        <p style="margin: 0 auto;">ビデオ通話に対する注意点　　※必ずお読みください</p>
      </div>
      <article class="message is-danger">
        <div class="message-body">
          <br>これは<strong>リアルタイムビデオ通話</strong>です。<strong>相手が不快になるような言動</strong>は避けましょう。
          <br>
          <br>"開始する"ボタンをクリックするとカメラが起動し、My-IDが発行されます。
          <br>
          <br><strong>通話相手があなたのIDを入力すると通話が始まります</strong>のでIDを送信する時はご注意ください。
          <br>
          <br><strong>画面の更新をかけるたびにIDは変化します。通話中にページの更新を行うと通話が切断されますのでご注意ください。</strong>
          <br>
          <br>あくまで分からない問題を教えあうためのビデオ通話です。
          <br>その他の目的での利用はお控えください。
          <br>
          <br>問題のあるアカウントの場合、利用を停止することもありますのでご注意ください。
          <br>
        </div>
      </article>
    </article>
    <button class="button is-rounded is-link", id="before-call", style="margin: 80px;">上記を確認して開始する</button>
  </div>
</div>

<script>
  document.getElementById("call-media-contents").style.display ="none";
  document.getElementById("before-call").addEventListener("click", function() {
    alert("カメラがオンになります");
    alert("IDが発行されます。相手に教えることでビデオ通話ができます");
    const contents = document.getElementById("call-media-contents");
    const button = document.getElementById("before-call-contents");
    if(contents.style.display=="block"){
      contents.style.display ="none";
      button.style.display ="block";
    }else{
      contents.style.display ="block";
      button.style.display ="none";
    }

    let localStream;

    navigator.mediaDevices.getUserMedia({video: true, audio: true})
      .then( stream => {
      const videoElm = document.getElementById('my-video')
      videoElm.srcObject = stream;
      videoElm.play();
      localStream = stream;
    }).catch( error => {
      console.error('mediaDevice.getUserMedia() error:', error);
      return;
    });

    const peer = new Peer({
      key: gon.api_key,
      debug: 3
    });
    peer.on('open', () => {
      document.getElementById('my-id').textContent = peer.id;
    });
    peer.on('error', err => {
      alert(err.message);
    });
    peer.on('close', () => {
    alert('通信が切断しました。');
    });

    document.getElementById('make-call').onclick = () => {
      const theirID = document.getElementById('their-id').value;
      const mediaConnection = peer.call(theirID, localStream);
      setEventListener(mediaConnection);
    };

    document.getElementById('stop-button').addEventListener("click", function() {
      location.reload();
    });

    const setEventListener = mediaConnection => {
      mediaConnection.on('stream', stream => {
        const videoElm = document.getElementById('their-video')
        videoElm.srcObject = stream;
        videoElm.play();
      });
    }
    peer.on('call', mediaConnection => {
      mediaConnection.answer(localStream);
      setEventListener(mediaConnection);
    });
  });
  function txtCopy() {
    const target = document.getElementById('my-id');
    if (navigator.userAgent.match(/ipad|ipod|iphone/i)) {
      target.readOnly = false;
      const range = document.createRange();
      range.selectNode(target);
      window.getSelection().addRange(range);
      document.execCommand('copy');
      target.readOnly = true;
    } else {
      target.select();
      document.execCommand('copy');
    }
    alert("My-IDをコピーしました。");
  }
  const trg = document.getElementById('copy-btn');
  trg.addEventListener('click',txtCopy);
</script>

app/views/tweets/edit.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ツイート編集
      </h1>
    </div>
  </div>
</section>


<% if @tweet.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @tweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @tweet do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "本文", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '更新する', class: "button is-link" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/tweets/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        質問一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @tweets.each do |tweet| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to tweet_path(tweet) do %>
                  <%= attachment_image_tag tweet, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= link_to user_path(tweet.user_id) do %>
                      <%= attachment_image_tag tweet.user, :profile_image, fallback: "no_image.png", class: "profile_image" %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to tweet.title.truncate(8, separator: '.'), tweet_path(tweet) %></div>
                </div>
              </div>
              <div class="content">
                <time><%= tweet.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate(@tweets) %>
  </div>
</section>

app/views/tweets/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @tweet.title%>
      </h1>
      <h2 class="subtitle">
        回答数：<%= @tweet.comments.count %>
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= link_to Refile.attachment_url(@tweet, :image), "data-lightbox"=>"a" do %>
                  <%= attachment_image_tag @tweet, :image, fallback: "no_image.png" %> 
              <% end %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @tweet.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>本文</th>
                </tr>
                <tr>
                  <td><%= simple_format @tweet.body %></td>
                </tr>
              </table>
              <% if @tweet.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_tweet_path(@tweet), class: "button is-link" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <%= link_to user_path(@tweet.user), class: "panel-block" do %>
            <%= attachment_image_tag @tweet.user, :profile_image, fallback: "no_image.png", class: "profile_image" %>
          <% end %>
          <p class="panel-heading">
            質問者： <%= link_to @tweet.user.username, user_path(@tweet.user), class:"has-text-white"%>
          </p>
          <div class="panel-block">
            <p class="control">
              自己紹介：<%= @tweet.user.profile %>
            </p>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>

<div class="column has-background-light">
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h1 class="title"">
          この質問の回答
        </h1>
      </div>
    </div>
  </section>
  <div class="column is-7">
    <% if @comments.present? %>
      <% @comments.each do |comment| %>
        <div class="card">
          <hr>
            <% if comment.image.present? %>
              <div class="card-image">
                <figure class="image is-4by3">
                  <%= link_to Refile.attachment_url(comment, :image), "data-lightbox"=>"ab" do %>
                    <%= attachment_image_tag comment, :image %>
                  <% end %>
                </figure>
              </div>
            <% else %>
            <% end %>
          <div class="card-content", style="margin-button">
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>回答：<%= link_to comment.user.username, "/users/#{comment.user_id}" %>さん</th>
                </tr>
                <tr>
                  <td><%= simple_format comment.text %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h1 class="subtitle1">まだ回答がありません</h1>
    <% end %>
  </div>
</div>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title"">
        あなたの回答を送信する
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <div class="field">
        <%= f.label :text, "本文", class: "label" %>
        <%= f.text_area :text, class: "textarea" %>
      </div>
      <div class="field">
        <%= f.label :image, "写真", class: "label" %>
        <%= f.attachment_field :image, class: "input" %>
      </div>
      <%= f.submit '回答する', class: "button is-link" %>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザーページ
      </h1>
      <h2 class="subtitle">
        質問数：<%= @user.tweets.count %>
      </h2>
      <h2 class="subtitle">
        回答数：<%= @user.comments.count %>
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
              <%= attachment_image_tag @user, :profile_image, fallback: "no_image.png", class: "profile_image" %>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                  <td class="is-size-4">
                    <%= @user.email %>
                  </td>
                  <td>
                      <%= link_to "編集", edit_user_path(@user), class: "button is-link" %>
                  </td>
                <% else %>
                  <td>
                      <% if @isRoom == true %>
                        <%= link_to "DMを送る", "/rooms/#{@roomId}", class: "button is-link" %>
                      <% else %>
                        <%= form_for @room do |f| %>
                          <%= fields_for @entry do |e| %>
                            <%= e.hidden_field :user_id, :value=> @user.id %>
                          <% end %>
                          <%= f.button "DMを開始する", class: "button is-link"%>
                        <% end %>
                      <% end %>
                  </td>
                <% end %>
              </tr>
            </table>
            <hr>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="column has-background-light">
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h1 class="title"">
          質問一覧
        </h1>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
        <% if @user.tweets.present? %>
          <% @user.tweets.each do |tweet| %>
            <div class="column is-4">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <%= link_to tweet_path(tweet) do %>
                      <%= attachment_image_tag tweet, :image, fallback: "no_image.png" %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4", style="text-align: center;">
                    <%= link_to tweet_path(tweet) do %>
                      <%= tweet.title.truncate(10, separator: '.') %>
                    <% end %>
                  </p>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-content">
                      <%= link_to tweet_path(tweet), class: "panel-block" do %>
                        <span class="panel-icon">
                          <i class="fas fa-book" aria-hidden="true"></i>
                        </span>
                        質問を見る
                      <% end %>
                      <% if @user.id == current_user.id %>
                        <%= link_to edit_tweet_path(tweet), class: "panel-block" do %>
                          <span class="panel-icon">
                            <i class="fas fa-edit"></i>
                          </span>
                          質問を編集する
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="content">
                    <time><%= tweet.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="non-tweet">
            <h1 class="subtitle1">まだ質問がありません</h1>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title"">
        このユーザーの回答一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <% if @comments.present? %>
      <% @comments.each do |comment| %>
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <%= link_to user_path(comment.tweet.user_id) do %>
                <%= attachment_image_tag comment.tweet.user, :profile_image, fallback: "no_image.png" %>
              <% end %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong><%= link_to comment.tweet.user.username, user_path(comment.tweet.user_id) %>さんの質問に回答しました</strong>
                <br>
                質問：<%= link_to comment.tweet.title,  tweet_path(comment.tweet_id) %>
              </p>
            </div>
            <% if comment.image.present? %>
              <div class="content">
                画像で回答を送信しました
              </div>
            <% else %>
              <div class="content">
                <%= comment.text %>
              </div>
            <% end %>
          </div>
        </article>
      <% end %>
      <hr>
    <% else %>
      <h1 class="subtitle1">まだ回答がありません</h1>
    <% end %>
  </div>
  <%= paginate @comments %>
</section>