config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users
  resources :messages, only: :create
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user 
  has_many :notifications, dependent: :destroy
  attachment :image
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, dependent: :destroy
  attachment :message_image
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :tweet, optional: true
  belongs_to :comment, optional: true
  belongs_to :message, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/room.rb
class Room < ApplicationRecord
  attachment :message_image
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end


  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      tweet_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :username, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(3)
    @comments = Comment.all.order("created_at DESC").page(params[:page]).per(7)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    gon.api_key = ENV['API_KEY']
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(6)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweet_path(@tweet), notice: "投稿しました"
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
    if @tweet.user != current_user
      redirect_to tweets_path, alert: "不正なアクセスです"
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet), notice: "更新しました"
    else
      render :edit
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :body, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.includes(:tweet).order("created_at DESC").page(params[:page]).per(10)
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
    @visitor = notification.visitor
    @visitor_comment = notification.comment_id
    case notification.action
      when "comment" then
        @comment = Comment.find_by(id: @visitor_comment)&.text
        tag.a(@visitor.username, href:user_path(@visitor), style:"font-weight: bold;")+"さんが"+tag.a('あなたの投稿', href:tweet_path(notification.tweet.id), style:"font-weight: bold;")+"に回答しました"
    end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Question</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <script src="https://cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script>
    <%= include_gon %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-172933058-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-172933058-1');
    </script>
    <script data-ad-client="ca-pub-4027371013900224" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

  </head>

  <body>
    <div class="nav", style="background-color: black">
      <nav class="navbar is-transparent is-black", style="max-width: 680px; margin: 0 auto;">
        <div class="navbar-brand">
          <%= link_to root_path, class:"navbar-item" do %>
            Own Question
          <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
        </div>
        <% if user_signed_in? %>
          <div id="navbarExampleTransparentExample", class="navbar-menu", style="background-color: black">
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <p class="control">
                    <%= link_to new_tweet_path, class:"button is-black" do %>
                      <span class="icon">
                        <i class="fab fa-twitter"></i>
                      </span>
                      <span>
                        質問する
                      </span>
                    <% end %>
                  </p>
                  <div class="navbar-item has-dropdown is-hoverable is-white">
                    <%= link_to '#', class:"navbar-link has-text-white" do %>
                      メニュー
                    <% end %>
                    <div class="navbar-dropdown is-right">
                      <%= link_to tweets_path, class:"navbar-item has-text-link" do %>
                        質問一覧
                      <% end %>
                      <% if unchecked_notifications.any? %>
                        <i class="fa fa-circle" style="color: gold;"></i>
                      <% end %>
                      <%= link_to notifications_path, class:"navbar-item has-text-link" do %>
                        通知
                      <% end %>
                      <hr class="navbar-divider">
                      <%= link_to user_path(current_user), class:"navbar-item has-text-link" do %>
                        マイページ
                      <% end %>
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item has-text-link", data: { confirm: 'ログアウトしますか？' } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div id="navbarExampleTransparentExample", class="navbar-menu", style="background-color: black">
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <p class="control">
                    <%= link_to new_user_session_path, class:"button is-black" do %>
                      <span>
                        ログイン
                      </span>
                    <% end %>
                  </p>
                  <div class="navbar-item has-dropdown is-hoverable is-white">
                    <%= link_to '#', class:"navbar-link has-text-white" do %>
                      メニュー
                    <% end %>
                    <div class="navbar-dropdown is-right">
                      <%= link_to tweets_path, class:"navbar-item has-text-link" do %>
                        ツイート一覧
                      <% end %>
                      <%= link_to new_tweet_path, class:"navbar-item has-text-link", id:"devise_alert" do %>
                        投稿する
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </nav>
    </div>

    <div class=main>
      <%= yield %>
    </div>
  </body>
</html>